.TH PS4PDF "1" "April 2006" "ps4pdf" "User Commands"
.SH NAME
ps4pdf \- a shell script for creating .pdf from .tex
.SH SYNOPSIS
.B ps4pdf [--version|-h|--help|-q|-v] file
.SH DESCRIPTION
.PP
ps4pdf creates a .pdf file from a .tex file by calling latex, dvips, and
ps2pdf.
.SH OPTIONS
.TP
file
.IP
The TeX file which should be compiled into a pdf document.
.TP
\fB\-\-help\fR \fB\-h\fR
.IP
Display a short help message
.TP
\fB\-\-version\fR
.IP
Display the version of the script.
.TP
\fB\-v\fR
.IP
Be a bit noisy.
.TP
\fB\-q\fR
.IP
Be silent.
.SH AUTHORS
.B ps4pdf
was written by Thomas Esser.
This manpage
was written by Norbert Preining for Debian/GNU Linux and may be used,
modified and/or distributed freely by anyone.
