.TH PDFCROP "1" "May 2006" "pdfcrop" "1.5, 2004/06/24 - Copyright (c) 2002, 2004 by Heiko Oberdiek"
.SH NAME
PDFCROP \- crop pdf files to their minimal size.
.SH SYNOPSIS
.B pdfcrop
[\fIOPTIONS\fR ...] \fBinput\fR[.pdf] [\FIoutput file\fR]
.SH DESCRIPTION
.B pdfcrop
is a utility to calculate and remove empty margins from each page in
the input PDF file.  The resulting output file occupies the minimal
paper size needed for the contents and is therefore suitable for
inclusion as a graphic
.SH OPTIONS
.TP
\fB\-\-help\fR
print usage
.TP
\fB\-\-version\fR
print version
.TP
\fB\-\-\fR(\fBno\fR)\fBverbose\fR
verbose printing                      (default: false)
.TP
\fB\-\-\fR(\fBno\fR)\fBdebug\fR
debug informations                    (default: false)
.TP
\fB\-\-gscmd\fR <name>
call of ghostscript                   (default: gs)
.TP
\fB\-\-pdftexcmd\fR <name>
call of pdfTeX                        (default: pdftex)
.TP
\fB\-\-margins\fR "<left> <top> <right> <bottom>"
(0 0 0 0)
add extra margins, unit is bp. If only one number is
given, then it is used for all margins, in the case
of two numbers they are also used for right and bottom.
.TP
\fB\-\-\fR(\fBno\fR)\fBclip
clipping support, if margins are set  (default: false)
.TP
\fB\-\-\fR(\fBno\fR)\fBhires
using `%%HiResBoundingBox' instead of `%%BoundingBox'   (default: false)
.TP
\fB\-\-papersize\fR <foo>
parameter for gs's \fB\-sPAPERSIZE=\fR<foo>,
use only with older gs versions <7.32
.SH EXAMPLES
.IP
pdfcrop \fB\-\-margins\fR 10 input.pdf output.pdf
.IP
pdfcrop \fB\-\-margins\fR '5 10 5 20' \fB\-\-clip\fR input.pdf output.pdf
.SH "AUTHORS"
.B pdfcrop
has been written by Heiko Oberdiek.  This manual page has been written
by Frank K\[:u]ster for the Debian/GNU Linux distribution and may be
freely used, modified and/or distributed by anyone.

